"""Annotation entry schema — non-blocking feedback channel for agents.

Each line in ~/.claude/annotations/{agent-name}.jsonl is one AnnotationEntry.

Writers (multiple entry points, one channel):
- User via /annotate skill or ./scripts/annotate.sh CLI
- Orchestrator relaying user intent
- PostToolUse hook routing peer_notify messages
- Quality gate hooks reporting failures
- Preference update hooks propagating changes

Reader (single):
- PostToolUse hook checks after EVERY tool call
- Injects unacknowledged entries via additionalContext
- Agent sees annotation on their very next tool call, no turn boundary wait

Design doc ref: "Layer 3: User Annotations" section, lines 271-276.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from ._constants import TracingMixin


AnnotationPriority = Literal[
    "critical",  # agent must stop current work and address immediately
    "normal",  # agent integrates into current work
    "fyi",  # agent acknowledges, no action required
]

AnnotationSource = Literal[
    "user",  # human via /annotate skill
    "cli",  # human via ./scripts/annotate.sh
    "orchestrator",  # orchestrator relaying user intent
    "peer_notify",  # peer_notify message routed through annotation channel
    "quality_gate",  # automated quality check failure
    "preference_update",  # new preference propagated to active agents
    "state_machine",  # emitted by state machine think annotation lifecycle
]


class AnnotationEntry(TracingMixin):
    """A single annotation — feedback injected into an agent's context mid-turn.

    The PostToolUse hook reads all entries where acknowledged=False and injects
    them via additionalContext. After injection, it sets acknowledged=True and
    writes acknowledged_at.
    """

    model_config = ConfigDict(extra="forbid")

    timestamp: datetime
    priority: AnnotationPriority
    message: str  # the annotation content
    annotation_id: str | None = Field(
        default=None,
        description="Unique ID for acknowledgment tracking. Format: ann-{sha256[:8]}. "
        "Generated by PostToolUse for critical annotations.",
    )
    source: AnnotationSource
    from_agent: str | None = Field(
        default=None,
        description="Sender agent ID for peer_notify, null for user/system sources",
    )
    target_agent: str = Field(
        description="Target agent ID or role name (resolved to ID by skill/hook)",
    )
    acknowledged: bool = False
    acknowledged_at: datetime | None = None
    related_files: list[str] | None = None  # files relevant to the annotation
    metadata: dict[str, Any] | None = None


class ThinkValidationResult(BaseModel):
    """Return value of validate_think() — structured validation outcome.

    Callers access fields via dict (model_dump()), so this model defines
    the contract without breaking existing dict-based access patterns.
    """

    model_config = ConfigDict(extra="forbid")

    complete: bool
    issues: list[str] = Field(default_factory=list)
    chosen: str | None = None


class ThinkValidationLogEntry(BaseModel):
    """Audit log entry written by validate_think() to decisions/{agent-id}.jsonl.

    Distinct from DecisionLogEntry which captures structured THOUGHT/CONSIDERED/CHOSEN
    sections from the Think tool itself. This captures the validation result
    (whether the think output was complete enough to clear the annotation).
    """

    model_config = ConfigDict(extra="forbid")

    timestamp: datetime
    agent_id: str
    state: str
    tool: str = "Think"
    complete: bool
    issues: list[str] | None = None
    chosen: str | None = None
